# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Folkebibliotekernes CMS
logo: "/assets/images/layout/ddf-logo-small.png"
email:
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
minimal_mistakes_skin: default
search: true
search_provider: algolia
algolia:
  application_id: 0DVITCE5YK
  index_name: prod_folkebibliotekernes_cms_manual
  search_only_api_key: d0da63a81606f093f2e7e4fc4cbef2b1
  powered_by: true
  nodes_to_index: 'h1,h2,h3,h4,h5,h6,p,blockquote,li'

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
collections_dir: sider

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

atom_feed:
  hide: true

# Collections
collections:
  administrator:
    output: true
    permalink: /:collection/:path/
  redaktoer:
    output: true
    permalink: /:collection/:path/
  udvikler:
    output: true
    permalink: /:collection/:path/

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: splash
      author_profile: false
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      toc: true
      toc_label: "Indhold på siden"
      author_profile: false
      read_time: false
      comments: false
      share: true
      related: true
      sidebar:
        title: "Redaktør manual"
        nav: "redaktoer"
  # _redaktoer
  - scope:
      path: ""
      type: redaktoer
    values:
      layout: single
      toc: true
      toc_label: "Indhold på siden"
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        title: "Redaktør manual"
        nav: "redaktoer"
 
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
